# ----
# Site

title: The Woman King Syllabus
url: "https://orchid-heron.cloudvent.net"
baseurl:
google_analytics_key:
google_maps_javascript_api_key:
disqus_shortname:

# Values for the jekyll-seo-tag gem (https://github.com/jekyll/jekyll-seo-tag)
logo: "https://womankingsyllabus.github.io/images/logo.png"
description: The Woman King Syllabus is an open educational resource meant to aid the study of the historical period and themes explored in the movie The Woman King.
author:
  name: Ana Lucia Araujo
  email: aaraujo@howard.edu
  twitter: araujohistorian
social:
  name: The Woman King Syllabus
  links:
    - https://slaveryarchive.wordpress.com/

# -----
# Build

timezone: Etc/UTC

paginate: 10
paginate_path: "/blog/:num/"


defaults:
  -
    scope:
      path: ""
    values:
      layout: page
      background_image_path: https://womankingsyllabus.github.io/images/logo.png
      image: https://womankingsyllabus.github.io/images/logo.png
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
      _options:
        content:
          width: 960
          height: 2000
      _comments:
        image: Shown in social shares and the blog list.
  -
    scope:
      path: ""
      type: "staff_members"
    values:
      _options:
        image:
          width: 440
          height: 440

permalink: pretty

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag


exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE

# -----------
# CloudCannon

_select_data:
  call_to_actions:
    - Contact
    - Blog
    - Map


_comments:
  large_header: Toggles the size of the top banner.
  show_in_navigation: Toggles a link in the top banner.
  author_staff_member: The staff member writing this post.
  call_to_action: Type of request shown at the bottom of this page.
  background_image_path: Image shown in the top banner, blank for the default.
  testimonials: Update, add or remove testimonials.
  map: Update the map location and display settings.
  latitude: Coordinates for the center marker on the map.
  longitude: Coordinates for the center marker on the map.
  zoom: The zoom level for the map.
  phone_extension: The digits after dialing the company phone.
  credentials: Shown as subtext on staff member summaries.
  contact_email_address: Address for the contact form to send to.
  new_window: Whether the link opens a new browser tab/window.
